#函數外有一個i變數
#函數內有一個j變數
#這個練習請把註解拿掉試試
i=10
def checkfun( ):
  #i=i+10 #產生錯誤
  print(i)
  j=11
  return
checkfun( )
#j=j+10  #產生錯誤
#print(j) #產生錯誤
